### ISSUE TITLE
Kashall's Beta Testing Thoughts

### ISSUE THREAD

**Issue by kashalls** [TechxArtisanStudio/Openterface_Mini-KVM_Hardware#2]
👋 Hi there!

I was invited to take part in the Beta Testing of Openterface last month, and I wanted to write a document to show my thoughts about the device all in one place, so this is where I will put it.

### 06/11/2024
After originally being accepted to participate in late May of this year, I received the device without any shipping damage. It was well sealed, and considering the travel distance from their studio overseas to the United States it had no other damage. Inside the wrapping was their custom made box with the kit inside.

Included in my beta kit was the Openterface dongle, some stickers, a VGA to HDMI conversion cable, a 3ft orange type c to c cable, a type c to USB with an adapter to type c, and a HDMI cable. I personally find all of the provided cables sturdy. The included zipper shell case has a nice touch on the outside, but lacks branding on the case. Some orange/black text on the shell of the case would be really appealing. The inside of the shell has a nice fabric to prevent scratching, but the border inside next to the zipper is kind of itchy.

The device once plugged in was immediately recognized by Windows and could actually be used as a webcam, if you wanted to share your display on Discord you could do that as well (without the mouse and keyboard capabilities). I had some trouble running the device on some embedded Linux kernels where the uvcvideo kernel module was not built in, but the default kernel from Ubuntu 22.04 LTS and higher have this enabled by default making it plug and play.

Windows seems to have an issue with Openterface when using it through front-panel usb slots. Kevin had told me it was because my case's usb 3.0 ports might have actually been a hub instead which can cause issues since Openterface is actually using a USB hub in its design. I tried using Openterface from an actual Type C port and as well from a independently powered USB hub which worked marvelously.

**Comment by RyanWor** [comment]
For what it's worth, I've been using the openterface with a MSI Z390 based Windows 11 desktop and it's been working great via the front USB-C on my Fractal Design case. As suggested, it might be a hub or a lower speed USB3 port on your case.

**Comment by kashalls** [comment]
> For what it's worth, I've been using the openterface with a MSI Z390 based Windows 11 desktop and it's been working great via the front USB-C on my Fractal Design case. As suggested, it might be a hub or a lower speed USB3 port on your case.

That's what I was looking into, it seems that all of my usb ports eventually cause this "reset" to happen with the device where openterface disconnects and reconnects to Windows, but this is solved once its plugged directly into the motherboard's usb c slot.
